### ISSUE TITLE
Compatible with SSR?

### ISSUE THREAD

**Issue by kamwing** [David-Desmaisons/Vue.Isotope#27]

**Comment by David-Desmaisons** [comment]
@kamwing Could you be more specific?

**Comment by kamwing** [comment]
Thank you @David-Desmaisons for your reply :)

I use Vue.Isotope in Nuxt.js Framework and follow Atinux‘s solution  on [this page](https://github.com/nuxt/nuxt.js/issues/414).

So i have the same warning from Vue:
`
[Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.
`

and here is my ssr result:
<a href="http://2017.mhb.cc/projects/project-02/" target="_blank">my project url</a>

![image](https://cloud.githubusercontent.com/assets/183904/26008182/4e08da88-3776-11e7-9f7b-ee8f980cf5a5.png)

**Comment by David-Desmaisons** [comment]
Hello @kamwing , I would say you should currently use the by-pass provided by [the thread you share](https://github.com/nuxt/nuxt.js/issues/414).

Indeed, vue.isotope needs a client-side rendering in order to create isotope objects. I am not convinced that adding nux.js specific code in vue.isotope is a good idea.
That said I will consider review PR including this functional, as long as code impact is minimal.
