### ISSUE TITLE
Combination Filters

### ISSUE THREAD

**Issue by ercgnclvs** [David-Desmaisons/Vue.Isotope#47]
[https://isotope.metafizzy.co/filtering.html#combination-filters](https://isotope.metafizzy.co/filtering.html#combination-filters) 

Is there support for combination filters?
Thanks.

**Comment by SadRebel1000** [comment]
I have found myself considering the same question. I would guess it's supported. I'm currently trying to find out if it is possible. If anyone has an example written already, it could be a nice addition for the fiddle examples.

**Comment by SadRebel1000** [comment]
I've been breaking my head around this for the last 2 days and did not find a solution.
I see two solutions, I don't know which one is feasible:

- the filter function in vue.isotope can accept multiple filter keys and combine the two filers in a combined result;
- somehow create a function that adds a filter to getFilterdata and then use it, in this way a filter can be created before sending it to vue.isotope

I think the first option needs changes in the vue.isotope (or this is already possible and I don't know how), the latter one is more a problem for outside vue.isotope but have yet to find a way to add a filter.

I was hoping to find a solution and post it here so I could finally give something instead of only asking the community, but alas.

**Comment by David-Desmaisons** [comment]
The combination of filter described is based on CSS filter which are not exposed but Vue.Isotope.
The solution 1 is not supported by the library and I don't have any plan to support it.
Solution 2 is certianly doable, but implementation may very depending on your use case.

**Comment by SadRebel1000** [comment]
Thank you for the information. I will look into the second solution then. The filters In my use case are not css related, but are based on information in a list in data. I will setup a fiddle if I can’t come up a solution myself.

**Comment by David-Desmaisons** [comment]
I am closing this one since it is not something I will provide. Please fell free to add example usage here.

**Comment by austriker27** [comment]
@SadRebel1000 did you ever find a solution for combination filters?

**Comment by SadRebel1000** [comment]
Sorry for my late reaction. Yes I ended up creating a solution like described in solution2. As David has mentioned the solution was very dependent on my use case. In principal I created for every parameter a seperate boolean which I combined into one main boolean which I used as the source for getFilterdata. The key was that in the function to change 1 parameter all other parameters also needed to be updated too before creating a main boolean as source for GetFilterdata. These other parameters (that did not change) I read from a list variable that saved all previous filter parameters.
